_wandb:
    value:
        cli_version: 0.19.6
        m: []
        python_version: 3.10.16
        t:
            "1":
                - 1
                - 5
                - 53
                - 55
                - 80
            "2":
                - 1
                - 5
                - 53
                - 55
                - 80
            "3":
                - 2
                - 16
                - 23
                - 55
            "4": 3.10.16
            "5": 0.19.6
            "8":
                - 5
            "12": 0.19.6
            "13": linux-x86_64
batch_size:
    value: 16
beta_cycle_length:
    value: 10
beta_dendrite:
    value: 1
beta_min:
    value: 0
beta_spine:
    value: 1
beta_strategy:
    value: monotonic
beta_warmup_frac:
    value: 0.5
epochs:
    value: 50
free_bits_lambda:
    value: 0.5
latent_dim_dendrite:
    value: 12
latent_dim_spine:
    value: 12
learning_rate:
    value: 0.001
num_filters:
    value:
        - 32
        - 64
        - 128
        - 192
patience:
    value: 15
samples_per_epoch:
    value: 32768
use_free_bits:
    value: true
val_mc_samples:
    value: 16
val_samples:
    value: 512
warmup_epochs:
    value: 5
weight_decay:
    value: 1e-05
